### ISSUE TITLE
Demo跑在Android7.0的三星S7Edge上找不到路径

### ISSUE THREAD

**Issue by prpr894** [HCDarren/DRouter#1]
Demo跑在Android7.0的三星S7Edge上找不到路径，华为的7.0的系统没问题，但是三星的不行，原生8.0也遇到过相同的问题，找不到路径。但是情况仅发生在自动打的debug包或者配置好的自动签名的release包，手动打包签名后的apk安装上不会出现这种情况。另外阿里家的Arouter一样的情况，大神给分析一波？

**Comment by prpr894** [comment]
关闭Android studio 的 InstantRun 就好了。。。

**Comment by StephenGiant** [comment]
clean后run 也一样没有这样的问题 因为as增量安装的缓存机制导致的 包括cmake
