### ISSUE TITLE
使用@Action注解，path路径按照Read.me中一样不成功，弹出Please check to the action name is correct

### ISSUE THREAD

**Issue by dajiba009** [HCDarren/DRouter#3]
按照Read.ME中的要求来配置，但是依然无法跳转model。确认Action中的@Path和要跳转action中的Path一样，都是ModelName

**Comment by dajiba009** [comment]
问题解决了，先说一下解决思路，源码是最好的教师。
先看源码，action()方法是跳转到DRouter中的action()，这里是报“Please check to the action name is correct”的位置
当moduleClassName为空的时候就会触发这个Toast，那么看searchModuleClassName()这个方法是获取moduleClassName
往里面看就发现，是通过扫描dex文件来找到包含com.drouter.assist.module这个包的文件，通过Debug发现确实没有。
这个时候卡住了，不知道如何往下走。经过一番查找发现应该通过注解解析生成的文件没有生成，导致这里为空，那么就推测是不是注解解析器的问题，直接看源码，果真发现根本没有进入这个ModuleProcessor这个解析类。
如何解决?
一顿查找后发现是我的gradle版本过高，gradle的版本是6.0+，不能直接使用自定义注解解析器
解决方案：在drouter-compiler中的Builder.gradle中注释掉implementation 'com.google.auto.service:auto-service:1.0-rc2'
引入
    annotationProcessor 'com.google.auto.service:auto-service:1.0-rc6'
    api 'com.google.auto.service:auto-service:1.0-rc6'
这两行代码就可以了，这样就可以使用自定义注解解析器

**Comment by StephenGiant** [comment]
我6.5 用1.0正式版autoservice 路由解析失败 我看它dex里有apt生成的类啊

**Comment by StephenGiant** [comment]
我6.5的gradle 这样不行 build发现在module的build里有这个类 但是打包的时候没有打进去 在app下也无法引用它

**Comment by dajiba009** [comment]
你看一下你的build中引用这个model是不是用了implementation，不要使用implementation，使用compile来引用这个model

**Comment by StephenGiant** [comment]
api 'com.squareup:javapoet:1.13.0'
    implementation 'com.google.auto.service:auto-service:1.0-rc6'
    annotationProcessor 'com.google.auto.service:auto-service:1.0-rc6'
这样可以
